### ISSUE TITLE
Proposal: Always use a namespace for master-specific flags

### ISSUE THREAD

**Issue by charleso** [ambiata/master#19]
Some _like_:

``` toml
[master]
runner = "..."

[master.foo]
runner = "..."

[build.foo]
PUBLISH= "true"
```
