### ISSUE TITLE
Support V4 inline table syntax

### ISSUE THREAD

**Issue by charleso** [ambiata/master#23]
Currently the Haskell version only support v3 (we believe). We should add support for v4, which will allow for [inline tables](https://github.com/toml-lang/toml#inline-table)

``` toml
[build.foo]
  master = {
    runner = "..."
  }
```

In addition to:

``` toml
[build.foo]
  [build.foo.master]
    runner = "..."
```
